# Generated by Django 3.0.14 on 2022-10-14 15:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_courseadditional_over_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursetype',
            options={'verbose_name': 'Course Type', 'verbose_name_plural': 'Course Types'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='dependency',
            options={'verbose_name': 'Depedency', 'verbose_name_plural': 'Dependencies'},
        ),
        migrations.AlterModelOptions(
            name='genericgroup',
            options={'verbose_name': 'generic group', 'verbose_name_plural': 'generic groups'},
        ),
        migrations.AlterModelOptions(
            name='grouptype',
            options={'verbose_name': 'group type', 'verbose_name_plural': 'groupe types'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'holiday', 'verbose_name_plural': 'holidays'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['abbrev'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'period', 'verbose_name_plural': 'periods'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'room type', 'verbose_name_plural': 'room types'},
        ),
        migrations.AlterModelOptions(
            name='structuralgroup',
            options={'verbose_name': 'structural group', 'verbose_name_plural': 'structural groups'},
        ),
        migrations.AlterModelOptions(
            name='trainingprogramme',
            options={'verbose_name': 'training programme', 'verbose_name_plural': 'training programmes'},
        ),
        migrations.AlterModelOptions(
            name='transversalgroup',
            options={'verbose_name': 'transversal group', 'verbose_name_plural': 'transversal groups'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name': 'week', 'verbose_name_plural': 'weeks'},
        ),
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.CharField(choices=[('m', 'Monday'), ('tu', 'Tuesday'), ('w', 'Wednesday'), ('th', 'Thursday'), ('f', 'Friday'), ('sa', 'Saturday'), ('su', 'Sunday')], default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='timegeneralsettings',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('m', 'Monday'), ('tu', 'Tuesday'), ('w', 'Wednesday'), ('th', 'Thursday'), ('f', 'Friday'), ('sa', 'Saturday'), ('su', 'Sunday')], max_length=2), size=None),
        ),
        migrations.AlterField(
            model_name='traininghalfday',
            name='day',
            field=models.CharField(choices=[('m', 'Monday'), ('tu', 'Tuesday'), ('w', 'Wednesday'), ('th', 'Thursday'), ('f', 'Friday'), ('sa', 'Saturday'), ('su', 'Sunday')], default='m', max_length=2),
        ),
    ]
