# Generated by Django 4.2 on 2024-02-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0092_auto_20230427_1007"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transversalgroup",
            name="parallel_groups",
            field=models.ManyToManyField(blank=True, to="base.transversalgroup"),
        ),
    ]
