# Generated by Django 4.2 on 2024-02-13 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0037_alter_user_first_name"),
        ("base", "0093_alter_transversalgroup_parallel_groups"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoursePreference",
            new_name="CourseAvailability",
        ),
        migrations.RenameModel(
            old_name="RoomPreference",
            new_name="RoomAvailability",
        ),
        migrations.RenameModel(
            old_name="UserPreference",
            new_name="UserAvailability",
        ),
    ]
