# Generated by Django 4.2 on 2024-02-13 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0096_courseavailability_clean_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseavailability",
            name="day",
        ),
        migrations.RemoveField(
            model_name="courseavailability",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="courseavailability",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="courseavailability",
            name="week",
        ),
        migrations.RemoveField(
            model_name="roomavailability",
            name="day",
        ),
        migrations.RemoveField(
            model_name="roomavailability",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="roomavailability",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="roomavailability",
            name="week",
        ),
        migrations.RemoveField(
            model_name="useravailability",
            name="day",
        ),
        migrations.RemoveField(
            model_name="useravailability",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="useravailability",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="useravailability",
            name="week",
        ),
    ]
