# Generated by Django 4.2 on 2024-02-13 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0097_remove_courseavailability_day_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseavailability",
            old_name="clean_day",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="courseavailability",
            old_name="clean_duration",
            new_name="duration",
        ),
        migrations.RenameField(
            model_name="courseavailability",
            old_name="clean_day_time",
            new_name="in_day_start_time",
        ),
        migrations.RenameField(
            model_name="roomavailability",
            old_name="clean_day",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="roomavailability",
            old_name="clean_duration",
            new_name="duration",
        ),
        migrations.RenameField(
            model_name="roomavailability",
            old_name="clean_day_time",
            new_name="in_day_start_time",
        ),
        migrations.RenameField(
            model_name="useravailability",
            old_name="clean_day",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="useravailability",
            old_name="clean_duration",
            new_name="duration",
        ),
        migrations.RenameField(
            model_name="useravailability",
            old_name="clean_day_time",
            new_name="in_day_start_time",
        ),
    ]
