# Generated by Django 4.2 on 2024-02-15 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0099_courseavailability_start_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseavailability",
            name="in_day_start_time",
        ),
        migrations.RemoveField(
            model_name="roomavailability",
            name="in_day_start_time",
        ),
        migrations.RemoveField(
            model_name="useravailability",
            name="in_day_start_time",
        ),
    ]
