# Generated by Django 4.2 on 2024-02-20 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0100_remove_courseavailability_in_day_start_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timegeneralsettings",
            name="day_finish_time",
        ),
        migrations.RemoveField(
            model_name="timegeneralsettings",
            name="lunch_break_finish_time",
        ),
        migrations.RemoveField(
            model_name="timegeneralsettings",
            name="lunch_break_start_time",
        ),
        migrations.AddField(
            model_name="timegeneralsettings",
            name="afternoon_start_time",
            field=models.TimeField(default=datetime.time(14, 15)),
        ),
        migrations.AddField(
            model_name="timegeneralsettings",
            name="day_end_time",
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name="timegeneralsettings",
            name="morning_end_time",
            field=models.TimeField(default=datetime.time(12, 30)),
        ),
        migrations.AlterField(
            model_name="timegeneralsettings",
            name="day_start_time",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name="timegeneralsettings",
            name="default_preference_duration",
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
        ),
    ]
