# Generated by Django 4.2 on 2024-02-20 09:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "base",
            "0102_rename_tmp_day_start_time_timegeneralsettings_day_start_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="day",
            field=models.CharField(
                choices=[
                    ("m", "monday"),
                    ("tu", "tuesday"),
                    ("w", "wednesday"),
                    ("th", "thursday"),
                    ("f", "friday"),
                    ("sa", "saturday"),
                    ("su", "sunday"),
                ],
                default="m",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="timegeneralsettings",
            name="days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("m", "monday"),
                        ("tu", "tuesday"),
                        ("w", "wednesday"),
                        ("th", "thursday"),
                        ("f", "friday"),
                        ("sa", "saturday"),
                        ("su", "sunday"),
                    ],
                    max_length=2,
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="traininghalfday",
            name="day",
            field=models.CharField(
                choices=[
                    ("m", "monday"),
                    ("tu", "tuesday"),
                    ("w", "wednesday"),
                    ("th", "thursday"),
                    ("f", "friday"),
                    ("sa", "saturday"),
                    ("su", "sunday"),
                ],
                default="m",
                max_length=2,
            ),
        ),
    ]
