# Generated by Django 4.2 on 2024-02-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0104_schedulingperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="timegeneralsettings",
            name="scheduling_period_mode",
            field=models.CharField(
                choices=[
                    ("d", "day"),
                    ("w", "week"),
                    ("m", "month"),
                    ("y", "year"),
                    ("c", "custom"),
                ],
                default="w",
                max_length=1,
            ),
        ),
    ]
