# Generated by Django 4.2 on 2024-02-21 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0105_timegeneralsettings_scheduling_period_mode"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Period",
            new_name="TrainingPeriod",
        ),
        migrations.AlterModelOptions(
            name="trainingperiod",
            options={
                "verbose_name": "training period",
                "verbose_name_plural": "training periods",
            },
        ),
        migrations.RemoveField(
            model_name="module",
            name="period",
        ),
    ]
