# Generated by Django 4.2 on 2024-02-21 05:44

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ("base", "0105_timegeneralsettings_scheduling_period_mode"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Period",
            new_name="TrainingPeriod",
        ),
        migrations.AlterModelOptions(
            name="trainingperiod",
            options={
                "verbose_name": "training period",
                "verbose_name_plural": "training periods",
            },
        ),
        migrations.AlterField(
            model_name="module",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="base.trainingperiod",
                verbose_name="training period",
            ),
        )
    ]
