# Generated by Django 4.2 on 2024-02-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0106_rename_period_trainingperiod_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="period",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.trainingperiod",
                verbose_name="training period",
            ),
        ),
    ]
