# Generated by Django 4.2 on 2024-02-21 08:07

import datetime as dt
from django.db import migrations, models


def transfer_duration(apps, schema_editor):
    Course = apps.get_model("base", "Course")
    for c in Course.objects.all():
        c.duration = dt.timedelta(minutes=c.type.duration)
        c.save()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0106_rename_period_trainingperiod_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.DurationField(default=dt.timedelta(seconds=3600)),
        ),
        migrations.RunPython(transfer_duration),
    ]
