# Generated by Django 3.0.14 on 2024-02-21 11:58

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0110_remove_coursetype_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestarttimeconstraint',
            name='course_type',
        ),
        migrations.AddField(
            model_name='coursestarttimeconstraint',
            name='department',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursestarttimeconstraint',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='mode',
            name='scheduling_mode',
            field=models.CharField(choices=[('d', 'day'), ('w', 'week'), ('m', 'month'), ('y', 'year'), ('c', 'custom')], default='w', max_length=1),
        ),
        migrations.RemoveField(
            model_name='coursestarttimeconstraint',
            name='allowed_start_times',
        ),
        migrations.AddField(
            model_name='coursestarttimeconstraint',
            name='allowed_start_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='transversalgroup',
            name='parallel_groups',
            field=models.ManyToManyField(blank=True, related_name='_transversalgroup_parallel_groups_+', to='base.TransversalGroup'),
        ),
    ]
