# Generated by Django 4.2 on 2024-02-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0114_courseavailability_is_default_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduletutorrepartition',
            old_name='scheduling_period',
            new_name='period',
        ),
    ]
