# Generated by Django 4.2 on 2024-02-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0115_rename_scheduling_period_moduletutorrepartition_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='period',
            new_name='training_period',
        ),
    ]
