# Generated by Django 4.2 on 2024-02-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0116_rename_period_module_training_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingperiod',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_periods', to='base.department'),
        ),
    ]
