# Generated by Django 4.2 on 2024-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0118_alter_trainingperiod_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="abbrev",
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="trainingprogramme",
            unique_together={("abbrev", "department")},
        ),
    ]
