# Generated by Django 4.2 on 2024-03-11 10:38

from django.db import migrations

def convert_nd_into_day_gap(apps, schema_editor):
    Dependency = apps.get_model('base', 'Dependency')
    for dep in Dependency.objects.all():
        if dep.ND:
            dep.day_gap = 1
            dep.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0119_alter_department_abbrev_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_nd_into_day_gap),
        migrations.RemoveField(
            model_name='dependency',
            name='ND',
        ),
    ]
