# Generated by Django 4.2 on 2024-03-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0120_remove_dependency_nd"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="edtversion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="edtversion",
            name="work_copy",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="edtversion",
            unique_together={("department", "period", "work_copy")},
        ),
    ]
