# Generated by Django 4.2 on 2024-03-15 07:52

from django.db import migrations, models
import django.db.models.deletion


def fill_version(apps, schema_editor):
    EdtVersion = apps.get_model("base", "EdtVersion")
    ScheduledCourse = apps.get_model("base", "ScheduledCourse")
    scs = ScheduledCourse.objects.all().distinct(
        "course__module__train_prog__department", "course__period", "work_copy"
    )
    EdtVersion.objects.all().delete()
    for sc_pattern in scs:
        v = EdtVersion.objects.create(
            department=sc_pattern.course.module.train_prog.department,
            period=sc_pattern.course.period,
            major=sc_pattern.work_copy,
        )
        for sc in ScheduledCourse.objects.filter(
            course__module__train_prog__department=v.department,
            course__period=v.period,
            work_copy=v.major,
        ):
            sc.version = v
            sc.save()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0122_rename_work_copy_edtversion_major_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledcourse",
            name="version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.edtversion",
            ),
        ),
        migrations.RunPython(fill_version),
        migrations.RemoveField(
            model_name="scheduledcourse",
            name="work_copy",
        ),
    ]
