# Generated by Django 4.2 on 2024-03-15 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0123_remove_scheduledcourse_work_copy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledcourse",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.edtversion"
            ),
        ),
    ]
