# Generated by Django 4.2 on 2024-03-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0124_alter_scheduledcourse_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcost',
            name='work_copy',
        ),
        migrations.RemoveField(
            model_name='groupfreehalfday',
            name='work_copy',
        ),
        migrations.RemoveField(
            model_name='tutorcost',
            name='work_copy',
        ),
        migrations.AddField(
            model_name='groupcost',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.edtversion'),
        ),
        migrations.AddField(
            model_name='groupfreehalfday',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.edtversion'),
        ),
        migrations.AddField(
            model_name='tutorcost',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.edtversion'),
        ),
    ]
