# Generated by Django 4.2 on 2024-03-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0097_remove_stabilizegroupscourses_work_copy_and_more'),
        ('base', '0125_remove_groupcost_work_copy_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EdtVersion',
            new_name='TimetableVersion',
        ),
    ]
