# Generated by Django 4.2 on 2024-03-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0126_rename_edtversion_timetableversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingperiod',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.department'),
        ),
    ]
