# Generated by Django 4.2 on 2024-03-28 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0127_alter_schedulingperiod_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groupfreehalfday",
            old_name="DJL",
            new_name="number",
        ),
    ]
