# Generated by Django 4.2 on 2024-03-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0128_rename_djl_groupfreehalfday_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="supp_tutor",
            new_name="supp_tutors",
        ),
    ]
