# Generated by Django 4.2 on 2024-03-30 07:46

import datetime
from django.db import migrations, models
from django.apps import apps


def unset_default(apps, schema_editor):
    scheduled_couse_model = apps.get_model("base", "ScheduledCourse")
    for sc in scheduled_couse_model.objects.all():
        sc.save()


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0129_rename_supp_tutor_course_supp_tutors"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="pay_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledcourse",
            name="date",
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AddField(
            model_name="scheduledcourse",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.RunPython(unset_default),
        migrations.AlterField(
            model_name="scheduledcourse",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime(1871, 3, 18, 0, 0)),
        ),
    ]
