# Generated by Django 4.2 on 2024-03-30 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0129_rename_supp_tutor_course_supp_tutors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursemodification",
            name="day_old",
        ),
        migrations.AddField(
            model_name="course",
            name="pay_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledcourse",
            name="date",
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AlterField(
            model_name="scheduledcourse",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime(1871, 3, 18, 0, 0)),
        ),
    ]
