# Generated by Django 4.2 on 2024-03-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0130_course_pay_duration_scheduledcourse_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursemodification",
            name="day_old",
        ),
    ]
