# Generated by Django 4.2 on 2024-03-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0130_remove_coursemodification_day_old_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timegeneralsettings",
            old_name="days",
            new_name="weekdays",
        ),
    ]
