# Generated by Django 4.2 on 2024-04-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0131_rename_days_timegeneralsettings_weekdays"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseavailability",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="roomavailability",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="useravailability",
            name="is_default",
        ),
    ]
