# Generated by Django 4.2 on 2024-02-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_backupmodif_course_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupmodif',
            name='day',
        ),
        migrations.RemoveField(
            model_name='backupmodif',
            name='week',
        ),
        migrations.RemoveField(
            model_name='backupmodif',
            name='year',
        ),
        migrations.RemoveField(
            model_name='backupmodif',
            name='start_time',
        ),
        migrations.AddField(
            model_name='backupmodif',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
