# Generated by Django 4.2 on 2024-03-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0003_remove_backupmodif_day_remove_backupmodif_week_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="backupmodif",
            old_name="supp_tutor_usernames",
            new_name="supp_tutors_usernames",
        ),
    ]
