FROM node:18-alpine

WORKDIR /front

COPY FlOpEDT-front /front

RUN rm -rf FlOpEDT-front/node_modules\
    && rm -rf FlOpEDT-front/dist\
    && rm -f FlOpEDT-front/package-lock.json

RUN yarn global add vite\
    && yarn install
