# Generated by Django 4.2 on 2024-02-23 07:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomreservation', '0002_roomreservationvalidationemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservationtype',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#95a5a6', image_field=None, max_length=25, samples=None),
        ),
    ]
