# Generated by Django 4.2 on 2024-03-05 14:39

from django.db import migrations, models
import datetime as dt

def combine_start_time_and_end_time_with_date(apps, schema_editor):
    RoomReservation = apps.get_model('roomreservation', 'RoomReservation')
    for reservation in RoomReservation.objects.all():
        reservation.start_time_tmp = dt.datetime.combine(reservation.date, reservation.start_time)
        reservation.end_time_tmp = dt.datetime.combine(reservation.date, reservation.end_time)
        reservation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('roomreservation', '0003_alter_roomreservationtype_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='end_time_tmp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='start_time_tmp',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(combine_start_time_and_end_time_with_date),
        migrations.RemoveField(
            model_name='roomreservation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='start_time',
        ),
        migrations.RenameField(
            model_name='roomreservation',
            old_name='end_time_tmp',
            new_name='end_time'
        ),
        migrations.RenameField(
            model_name='roomreservation',
            old_name='start_time_tmp',
            new_name='start_time'
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
