# Generated by Django 4.2 on 2024-03-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roomreservation", "0004_alter_roomreservation_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationperiodicitybymonth",
            name="bm_x_choice",
            field=models.SmallIntegerField(
                choices=[
                    (1, "First"),
                    (2, "Second"),
                    (3, "Third"),
                    (4, "Fourth"),
                    (-2, "Penultimate"),
                    (-1, "Last"),
                ]
            ),
        ),
    ]
