# Generated by Django 4.2 on 2024-02-23 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalpresence',
            name='day',
        ),
        migrations.RemoveField(
            model_name='physicalpresence',
            name='week',
        ),
        migrations.AddField(
            model_name='physicalpresence',
            name='date',
            field=models.DateField(default=datetime.date(1789, 7, 14)),
        ),
    ]
