# Generated by Django 4.2 on 2024-02-26 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0038_remove_physicalpresence_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorpreference',
            name='max_hours_per_day',
        ),
        migrations.RemoveField(
            model_name='tutorpreference',
            name='min_hours_per_day',
        ),
        migrations.RemoveField(
            model_name='tutorpreference',
            name='pref_hours_per_day',
        ),
        migrations.AddField(
            model_name='tutorpreference',
            name='max_hours_per_day',
            field=models.DurationField(default=datetime.timedelta(seconds=32400), verbose_name='How much teaching time per day can you suffer ?'),
        ),
        migrations.AddField(
            model_name='tutorpreference',
            name='min_hours_per_day',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Under how  much teaching time per day would you prefer to avoid to have class?'),
        ),
        migrations.AddField(
            model_name='tutorpreference',
            name='pref_hours_per_day',
            field=models.DurationField(default=datetime.timedelta(seconds=14400), verbose_name='How much teaching time per day would you prefer ?'),
        ),
    ]
