# Generated by Django 4.2 on 2024-02-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0039_alter_tutorpreference_max_hours_per_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorpreference',
            old_name='max_hours_per_day',
            new_name='max_time_per_day',
        ),
        migrations.RenameField(
            model_name='tutorpreference',
            old_name='min_hours_per_day',
            new_name='min_time_per_day',
        ),
        migrations.RenameField(
            model_name='tutorpreference',
            old_name='pref_hours_per_day',
            new_name='pref_time_per_day',
        ),
    ]
