# Generated by Django 3.0.14 on 2023-03-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_auto_20221124_2149'),
        ('TTapp', '0075_auto_20230112_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nogroupcourseonday',
            name='course_types',
            field=models.ManyToManyField(related_name='no_course_on_days', to='base.CourseType'),
        ),
    ]
