# Generated by Django 3.0.14 on 2023-03-14 09:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_auto_20221124_2149'),
        ('TTapp', '0075_auto_20230112_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nogroupcourseonday',
            options={},
        ),
        migrations.RemoveField(
            model_name='nogroupcourseonday',
            name='course_types',
        ),
        migrations.CreateModel(
            name='NoGroupCourseTypeOnDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('title', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('modified_at', models.DateField(auto_now=True)),
                ('fampm_period', models.CharField(choices=[('fd', 'Full day'), ('AM', 'AM'), ('PM', 'PM')], max_length=2, verbose_name='fampm_period')),
                ('weekday', models.CharField(choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], max_length=2)),
                ('course_types', models.ManyToManyField(related_name='no_course_types_on_days', to='base.CourseType')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
                ('groups', models.ManyToManyField(blank=True, to='base.StructuralGroup')),
                ('train_progs', models.ManyToManyField(blank=True, to='base.TrainingProgramme')),
                ('weeks', models.ManyToManyField(blank=True, to='base.Week')),
            ],
            options={
                'verbose_name': 'No courses on declared days for groups',
                'verbose_name_plural': 'No courses on declared days for groups',
            },
        ),
    ]
