# Generated by Django 3.0.14 on 2023-09-29 11:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_auto_20221124_2149'),
        ('people', '0036_notificationspreferences_notify_other_user_modifications'),
        ('TTapp', '0076_auto_20230314_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='locateallcourses',
            name='room_types',
            field=models.ManyToManyField(blank=True, to='base.RoomType'),
        ),
        migrations.AddField(
            model_name='locateallcourses',
            name='tutors',
            field=models.ManyToManyField(blank=True, to='people.Tutor'),
        ),
        migrations.AlterField(
            model_name='tutorslunchbreak',
            name='end_lunch_time',
            field=models.PositiveSmallIntegerField(help_text='end lunch time'),
        ),
        migrations.AlterField(
            model_name='tutorslunchbreak',
            name='lunch_length',
            field=models.PositiveSmallIntegerField(help_text='minimal lunch length (in min)'),
        ),
        migrations.AlterField(
            model_name='tutorslunchbreak',
            name='start_lunch_time',
            field=models.PositiveSmallIntegerField(help_text='start lunch time'),
        ),
        migrations.AlterField(
            model_name='tutorslunchbreak',
            name='tutors',
            field=models.ManyToManyField(blank=True, help_text='considered tutors', related_name='lunch_breaks_constraints', to='people.Tutor'),
        ),
        migrations.AlterField(
            model_name='tutorslunchbreak',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], max_length=2), blank=True, help_text='considered week days', null=True, size=None),
        ),
    ]
