# Generated by Django 4.2 on 2024-02-13 08:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0037_alter_user_first_name"),
        ("TTapp", "0076_auto_20230314_1805"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorslunchbreak",
            name="end_lunch_time",
            field=models.PositiveSmallIntegerField(help_text="end lunch time"),
        ),
        migrations.AlterField(
            model_name="tutorslunchbreak",
            name="lunch_length",
            field=models.PositiveSmallIntegerField(
                help_text="minimal lunch length (in min)"
            ),
        ),
        migrations.AlterField(
            model_name="tutorslunchbreak",
            name="start_lunch_time",
            field=models.PositiveSmallIntegerField(help_text="start lunch time"),
        ),
        migrations.AlterField(
            model_name="tutorslunchbreak",
            name="tutors",
            field=models.ManyToManyField(
                blank=True,
                help_text="considered tutors",
                related_name="lunch_breaks_constraints",
                to="people.tutor",
            ),
        ),
        migrations.AlterField(
            model_name="tutorslunchbreak",
            name="weekdays",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("m", "monday"),
                        ("tu", "tuesday"),
                        ("w", "wednesday"),
                        ("th", "thursday"),
                        ("f", "friday"),
                        ("sa", "saturday"),
                        ("su", "sunday"),
                    ],
                    max_length=2,
                ),
                blank=True,
                help_text="considered week days",
                null=True,
                size=None,
            ),
        ),
    ]
