# Generated by Django 3.0.14 on 2024-02-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0112_remove_timegeneralsettings_default_availability_duration'),
        ('TTapp', '0077_alter_tutorslunchbreak_end_lunch_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parallelizecourses',
            name='course_types',
        ),
        migrations.RemoveField(
            model_name='parallelizecourses',
            name='modules',
        ),
        migrations.AddField(
            model_name='parallelizecourses',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CourseType'),
        ),
        migrations.AddField(
            model_name='parallelizecourses',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Module'),
        ),
    ]
