# Generated by Django 3.0.14 on 2023-12-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_auto_20221124_2149'),
        ('TTapp', '0077_auto_20230929_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nogroupcourseonday',
            name='course_types',
            field=models.ManyToManyField(blank=True, related_name='no_course_on_days', to='base.CourseType'),
        ),
    ]
