# Generated by Django 4.2 on 2024-02-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0112_remove_timegeneralsettings_default_availability_duration'),
        ('TTapp', '0078_auto_20240221_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignallcourses',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='avoidbothtimessameday',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='avoidstarttimes',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='boundphysicalpresencehalfdays',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='breakaroundcoursetype',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='considerdependencies',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='considerpivots',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='considerroomsorts',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='considertutorsunavailability',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='curfew',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='customconstraint',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='groupslunchbreak',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='groupsminhoursperday',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limitcoursetypetimeperperiod',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limitedroomchoices',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limitgroupmoves',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limitgroupsphysicalpresence',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limitgroupstimeperperiod',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limitholes',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limitmodulestimeperperiod',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limitsimultaneouscoursesnumber',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limitsimultaneousroomcourses',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limitstarttimechoices',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limittutormoves',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limittutorstimeperperiod',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limittutortimeperweeks',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='limitundesiredslotsperweek',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='locateallcourses',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='lowerboundbusydays',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='mingroupshalfdays',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='minimizebusydays',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='minmoduleshalfdays',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='minnonpreferedtrainprogsslot',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='minnonpreferedtutorsslot',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='mintutorshalfdays',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='modulesbybloc',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='nogroupcourseonday',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='nosimultaneousgroupcourses',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='notaloneforthesecousetypes',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='notutorcourseonday',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='novisio',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='parallelizecourses',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='respectmaxhoursperday',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='respecttutorsminhoursperday',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='scheduleallcourses',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='simultaneouscourses',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='stabilizationthroughweeks',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='stabilizegroupscourses',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='stabilizetutorscourses',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='tutorslunchbreak',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='visioonly',
            name='weeks',
        ),
        migrations.AddField(
            model_name='assignallcourses',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='avoidbothtimessameday',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='avoidstarttimes',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='boundphysicalpresencehalfdays',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='breakaroundcoursetype',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='considerdependencies',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='considerpivots',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='considerroomsorts',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='considertutorsunavailability',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='curfew',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='customconstraint',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='groupslunchbreak',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='groupsminhoursperday',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limitcoursetypetimeperperiod',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limitedroomchoices',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limitgroupmoves',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limitgroupsphysicalpresence',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limitgroupstimeperperiod',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limitholes',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limitmodulestimeperperiod',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limitsimultaneouscoursesnumber',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limitsimultaneousroomcourses',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limitstarttimechoices',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limittutormoves',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limittutorstimeperperiod',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limittutortimeperweeks',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='limitundesiredslotsperweek',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='locateallcourses',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='lowerboundbusydays',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='mingroupshalfdays',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='minimizebusydays',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='minmoduleshalfdays',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='minnonpreferedtrainprogsslot',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='minnonpreferedtutorsslot',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='mintutorshalfdays',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='modulesbybloc',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='nogroupcourseonday',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='nosimultaneousgroupcourses',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='notaloneforthesecousetypes',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='notutorcourseonday',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='novisio',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='parallelizecourses',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='respectmaxhoursperday',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='respecttutorsminhoursperday',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='scheduleallcourses',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='simultaneouscourses',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='stabilizationthroughweeks',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='stabilizegroupscourses',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='stabilizetutorscourses',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='tutorslunchbreak',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
        migrations.AddField(
            model_name='visioonly',
            name='periods',
            field=models.ManyToManyField(blank=True, to='base.schedulingperiod'),
        ),
    ]
