# Generated by Django 3.0.14 on 2023-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0079_nogroupcourseonday_transversal_groups_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignallcourses',
            name='pre_assigned_only',
            field=models.BooleanField(default=False, verbose_name='pre_assigned_only'),
        ),
        migrations.AlterField(
            model_name='groupsminhoursperday',
            name='min_hours',
            field=models.PositiveSmallIntegerField(verbose_name='min_hours'),
        ),
        migrations.AlterField(
            model_name='limitsimultaneousroomcourses',
            name='can_combine_two_groups_if_no_tutor',
            field=models.BooleanField(default=False, verbose_name='Can combine two groups if no tutor'),
        ),
        migrations.AlterField(
            model_name='parallelizecourses',
            name='desired_busy_slots_duration',
            field=models.PositiveSmallIntegerField(verbose_name='Desired busy slots duration'),
        ),
    ]
