# Generated by Django 4.2 on 2024-02-24 09:47

from django.db import migrations, models
import datetime as dt

def fill_end_times_and_lunch_lengths(apps, schema_editor):
    GroupLunchBreak = apps.get_model('TTapp', 'GroupsLunchBreak')
    TutorLunchBreak = apps.get_model('TTapp', 'TutorsLunchBreak')
    for lunch_break in set(GroupLunchBreak.objects.all()) | set(TutorLunchBreak.objects.all()):
        lunch_length_tmp = dt.timedelta(minutes = lunch_break.lunch_length)
        start_lunch_time_tmp = dt.time(hour = lunch_break.start_lunch_time//60, minute = lunch_break.start_lunch_time%60)
        end_lunch_time_tmp = dt.time(hour = lunch_break.end_lunch_time//60, minute = lunch_break.end_lunch_time%60)
        lunch_break.lunch_length_tmp = lunch_length_tmp
        lunch_break.start_lunch_time_tmp = start_lunch_time_tmp
        lunch_break.end_lunch_time_tmp = end_lunch_time_tmp
        lunch_break.save()

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0038_remove_physicalpresence_day_and_more'),
        ('base', '0114_courseavailability_is_default_and_more'),
        ('TTapp', '0079_remove_assignallcourses_weeks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LimitUndesiredSlotsPerWeek',
            new_name='LimitUndesiredSlotsPerPeriod',
        ),
        migrations.RenameModel(
            old_name='NoGroupCourseOnDay',
            new_name='NoGroupCourseOnWeekDay',
        ),
        migrations.RenameModel(
            old_name='NoTutorCourseOnDay',
            new_name='NoTutorCourseOnWeekDay',
        ),
        migrations.RenameModel(
            old_name='StabilizationThroughWeeks',
            new_name='StabilizationThroughPeriods',
        ),
        migrations.AlterModelOptions(
            name='limitundesiredslotsperperiod',
            options={'verbose_name': 'Limit undesired slots per period', 'verbose_name_plural': 'Limit undesired slots per period'},
        ),
        migrations.AlterModelOptions(
            name='nogroupcourseonweekday',
            options={'verbose_name': 'No courses on declared week days for groups', 'verbose_name_plural': 'No courses on declared week days for groups'},
        ),
        migrations.AlterModelOptions(
            name='stabilizationthroughperiods',
            options={'verbose_name': 'Stabilization through periods', 'verbose_name_plural': 'Stabilization through periods'},
        ),
        migrations.RenameField(
            model_name='limitholes',
            old_name='max_holes_per_week',
            new_name='max_holes_per_period',
        ),
        migrations.AddField(
            model_name='groupslunchbreak',
            name='end_lunch_time_tmp',
            field=models.TimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='groupslunchbreak',
            name='lunch_length_tmp',
            field=models.DurationField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='groupslunchbreak',
            name='start_lunch_time_tmp',
            field=models.TimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='tutorslunchbreak',
            name='end_lunch_time_tmp',
            field=models.TimeField(help_text='end lunch time', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='tutorslunchbreak',
            name='lunch_length_tmp',
            field=models.DurationField(help_text='minimal lunch length', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='tutorslunchbreak',
            name='start_lunch_time_tmp',
            field=models.TimeField(help_text='start lunch time', null=True, blank=True),
        ),
        migrations.RunPython(fill_end_times_and_lunch_lengths),
        migrations.RemoveField(
            model_name='groupslunchbreak',
            name='end_lunch_time',
        ),
        migrations.RemoveField(
            model_name='groupslunchbreak',
            name='lunch_length',
        ),
        migrations.RemoveField(
            model_name='groupslunchbreak',
            name='start_lunch_time',
        ),
        migrations.RemoveField(
            model_name='tutorslunchbreak',
            name='end_lunch_time',
        ),
        migrations.RemoveField(
            model_name='tutorslunchbreak',
            name='lunch_length',
        ),
        migrations.RemoveField(
            model_name='tutorslunchbreak',
            name='start_lunch_time',
        ),
        migrations.RenameField(
            model_name='groupslunchbreak',
            old_name='end_lunch_time_tmp',
            new_name='end_lunch_time',
            ),
        migrations.RenameField(
            model_name='groupslunchbreak',
            old_name='lunch_length_tmp',
            new_name='lunch_length',
        ),
        migrations.RenameField(
            model_name='groupslunchbreak',
            old_name='start_lunch_time_tmp',
            new_name='start_lunch_time',
        ),
        migrations.RenameField(
            model_name='tutorslunchbreak',
            old_name='end_lunch_time_tmp',
            new_name='end_lunch_time',
        ),
        migrations.RenameField(
            model_name='tutorslunchbreak',
            old_name='lunch_length_tmp',
            new_name='lunch_length',
        ),
        migrations.RenameField(
            model_name='tutorslunchbreak',
            old_name='start_lunch_time_tmp',
            new_name='start_lunch_time',
        ),
    ]
