# Generated by Django 4.2 on 2024-02-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0080_rename_limitundesiredslotsperweek_limitundesiredslotsperperiod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupslunchbreak',
            name='end_lunch_time',
            field=models.TimeField(default='14:15:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupslunchbreak',
            name='lunch_length',
            field=models.DurationField(default='1:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupslunchbreak',
            name='start_lunch_time',
            field=models.TimeField(default='11:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorslunchbreak',
            name='end_lunch_time',
            field=models.TimeField(default='14:15:00', help_text='end lunch time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorslunchbreak',
            name='lunch_length',
            field=models.DurationField(default='1:00:00', help_text='minimal lunch length'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorslunchbreak',
            name='start_lunch_time',
            field=models.TimeField(default='11:30:00', help_text='start lunch time'),
            preserve_default=False,
        ),
    ]
