# Generated by Django 4.2 on 2024-02-25 14:02

from django.db import migrations, models
import datetime as dt

def fill_time1_and_time2(apps, schema_editor):
    AvoidBothTimesSameDay = apps.get_model('TTapp', 'AvoidBothTimesSameDay')
    for avoid_both in AvoidBothTimesSameDay.objects.all() :
        avoid_both.time1_tmp = dt.time(hour=avoid_both.time1//60, minute=avoid_both.time1%60)
        avoid_both.time2_tmp = dt.time(hour=avoid_both.time2//60, minute=avoid_both.time2%60)
        avoid_both.save()

class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0081_alter_groupslunchbreak_end_lunch_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoidbothtimessameday',
            name='time1_tmp',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='avoidbothtimessameday',
            name='time2_tmp',
            field=models.TimeField(null=True),
        ),
        migrations.RunPython(fill_time1_and_time2),
        migrations.RemoveField(
            model_name='avoidbothtimessameday',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='avoidbothtimessameday',
            name='time2',
        ),
        migrations.RenameField(
            model_name='avoidbothtimessameday',
            old_name='time1_tmp',
            new_name='time1',
            ),
        migrations.RenameField(
            model_name='avoidbothtimessameday',
            old_name='time2_tmp',
            new_name='time2',
        ),
        migrations.AlterField(
            model_name='avoidbothtimessameday',
            name='time1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='avoidbothtimessameday',
            name='time2',
            field=models.TimeField(),
        )
    ]
