# Generated by Django 4.2 on 2024-02-26 03:41

from django.db import migrations, models
import datetime as dt

class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0083_alter_breakaroundcoursetype_min_break_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitundesiredslotsperperiod',
            name='slot_end_time',
        ),
        migrations.RemoveField(
            model_name='limitundesiredslotsperperiod',
            name='slot_start_time',
        ),
        migrations.AddField(
            model_name='limitundesiredslotsperperiod',
            name='slot_end_time',
            field=models.TimeField(default=dt.time(hour=8)),
        ),
        migrations.AddField(
            model_name='limitundesiredslotsperperiod',
            name='slot_start_time',
            field=models.TimeField(default=dt.time(hour=10)),
        ),
    ]
