# Generated by Django 4.2 on 2024-02-26 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0085_alter_curfew_curfew_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsminhoursperday',
            options={'verbose_name': 'Respect groups min time per day bounds', 'verbose_name_plural': 'Respect groups min time per day bounds'},
        ),
        migrations.RemoveField(
            model_name='groupsminhoursperday',
            name='min_hours',
        ),
        migrations.AddField(
            model_name='groupsminhoursperday',
            name='min_time',
            field=models.DurationField(default=datetime.timedelta(seconds=10800)),
        ),
    ]
