# Generated by Django 4.2 on 2024-02-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0040_rename_max_hours_per_day_tutorpreference_max_time_per_day_and_more'),
        ('base', '0116_rename_period_module_training_period'),
        ('TTapp', '0087_rename_respectmaxhoursperday_respectmaxtimeperday_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MinimizeBusyDays',
            new_name='MinimizeTutorsBusyDays',
        ),
        migrations.RenameModel(
            old_name='RespectMaxTimePerDay',
            new_name='RespectTutorsMaxTimePerDay',
        ),
    ]
