# Generated by Django 4.2 on 2024-02-28 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0116_rename_period_module_training_period'),
        ('TTapp', '0088_rename_minimizebusydays_minimizetutorsbusydays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parallelizecourses',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='parallelizecourses',
            name='module',
        ),
        migrations.AddField(
            model_name='parallelizecourses',
            name='course_types',
            field=models.ManyToManyField(blank=True, to='base.coursetype'),
        ),
        migrations.AddField(
            model_name='parallelizecourses',
            name='modules',
            field=models.ManyToManyField(blank=True, to='base.module'),
        ),
        migrations.AlterField(
            model_name='assignallcourses',
            name='pre_assigned_only',
            field=models.BooleanField(default=False, verbose_name='Pre-assigned courses only'),
        ),
        migrations.AlterField(
            model_name='groupsminhoursperday',
            name='min_time',
            field=models.DurationField(default=datetime.timedelta(seconds=10800), verbose_name='min_time'),
        ),
    ]
