# Generated by Django 4.2 on 2024-03-02 14:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0090_remove_breakaroundcoursetype_train_progs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avoidstarttimes',
            name='forbidden_start_times',
        ),
        migrations.RemoveField(
            model_name='limitstarttimechoices',
            name='possible_start_times',
        ),
        migrations.AddField(
            model_name='avoidstarttimes',
            name='forbidden_start_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='limitstarttimechoices',
            name='possible_start_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=None),
        ),
    ]
