# Generated by Django 4.2 on 2024-03-09 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0091_alter_avoidstarttimes_forbidden_start_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakaroundcoursetype',
            name='min_break_length',
        ),
        migrations.AddField(
            model_name='breakaroundcoursetype',
            name='min_break_after',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=900), null=True),
        ),
        migrations.AddField(
            model_name='breakaroundcoursetype',
            name='min_break_before',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=900), null=True),
        ),
    ]
