# Generated by Django 4.2 on 2024-03-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0120_remove_dependency_nd'),
        ('people', '0040_rename_max_hours_per_day_tutorpreference_max_time_per_day_and_more'),
        ('TTapp', '0094_considermoduletutorrepartitions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LimitUndesiredSlotsPerPeriod',
            new_name='LimitUndesiredSlotsPerDayPeriod',
        ),
    ]
