# Generated by Django 4.2 on 2024-03-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TTapp", "0097_remove_stabilizegroupscourses_work_copy_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomConstraint",
        ),
    ]
