# Generated by Django 4.2 on 2024-03-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0131_rename_days_timegeneralsettings_weekdays"),
        ("TTapp", "0098_delete_customconstraint"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GroupsMinHoursPerDay",
            new_name="GroupsMinTimePerDay",
        ),
    ]
