# Generated by Django 4.2 on 2024-04-01 14:27

from django.db import migrations, models
import datetime as dt


def replace_max_hours_by_max_time(apps, schema_editor):
    LimitCourseTypeTimePerPeriod = apps.get_model(
        "TTapp", "LimitCourseTypeTimePerPeriod"
    )
    LimitGroupsTimePerPeriod = apps.get_model("TTapp", "LimitGroupsTimePerPeriod")
    LimitModulesTimePerPeriod = apps.get_model("TTapp", "LimitModulesTimePerPeriod")
    LimitTutorsTimePerPeriod = apps.get_model("TTapp", "LimitTutorsTimePerPeriod")

    for model in [
        LimitCourseTypeTimePerPeriod,
        LimitGroupsTimePerPeriod,
        LimitModulesTimePerPeriod,
        LimitTutorsTimePerPeriod,
    ]:
        for obj in model.objects.all():
            obj.max_time = dt.timedelta(hours=obj.max_hours)
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("TTapp", "0099_rename_groupsminhoursperday_groupsmintimeperday"),
    ]

    operations = [
        migrations.AddField(
            model_name="limitcoursetypetimeperperiod",
            name="max_time",
            field=models.DurationField(
                default=dt.timedelta(hours=2), verbose_name="max_time"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="limitgroupstimeperperiod",
            name="max_time",
            field=models.DurationField(
                default=dt.timedelta(hours=2), verbose_name="max_time"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="limitmodulestimeperperiod",
            name="max_time",
            field=models.DurationField(
                default=dt.timedelta(hours=2), verbose_name="max_time"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="limittutorstimeperperiod",
            name="max_time",
            field=models.DurationField(
                default=dt.timedelta(hours=2), verbose_name="max_time"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(replace_max_hours_by_max_time),
        migrations.RemoveField(
            model_name="limitcoursetypetimeperperiod",
            name="max_hours",
        ),
        migrations.RemoveField(
            model_name="limitgroupstimeperperiod",
            name="max_hours",
        ),
        migrations.RemoveField(
            model_name="limitmodulestimeperperiod",
            name="max_hours",
        ),
        migrations.RemoveField(
            model_name="limittutorstimeperperiod",
            name="max_hours",
        ),
    ]
