# Generated by Django 4.2 on 2024-05-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0132_remove_courseavailability_is_default_and_more"),
        ("TTapp", "0102_limitmodulestimeperperiod_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="limitsimultaneouscoursesnumber",
            name="train_progs",
            field=models.ManyToManyField(
                blank=True, null=True, to="base.trainingprogramme"
            ),
        ),
    ]
