# Generated by Django 4.2 on 2024-02-23 07:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displayweb', '0005_auto_20210831_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakingnews',
            name='fill_color',
            field=colorfield.fields.ColorField(default='#228B22', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='breakingnews',
            name='strk_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='moduledisplay',
            name='color_bg',
            field=colorfield.fields.ColorField(default='#D3D3D3', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='moduledisplay',
            name='color_txt',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='tutordisplay',
            name='color_bg',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='tutordisplay',
            name='color_txt',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
